config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :destroy]
  resources :uploaded_files do
    resources :comments, only: [:index]
  end
  get '/uploaded_files/:id/download', to: 'uploaded_files#download'
  root 'application#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :uploaded_file
  belongs_to :parent, class_name: 'Comment'
  has_many :comments, foreign_key: :parent_id

  def self.top_level
    where(parent_id: nil)
  end

  def self.best
    order(score: :desc)
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :uploaded_file_tags
  has_many :uploaded_files, through: :uploaded_file_tags
end

app/models/uploaded_file.rb
class UploadedFile < ActiveRecord::Base

  belongs_to :user
  has_many :uploaded_file_tags
  has_many :tags, through: :uploaded_file_tags
  has_many :comments

  def tags_str=(tagsStr)
    tags.clear
    tagsStr.split(',').each do |tag|
      tags << Tag.find_or_create_by(name: tag.strip)
    end
  end

  def tags_str
    return tags.collect{ |t| t.name }.join(', ')
  end

  def related
    UploadedFile.where.not(id: id).joins(:tags).where('tags.name' => tags.collect{ |t| t.name }).group(:id).order('COUNT(uploaded_files.id) DESC')
  end

end

app/models/uploaded_file_tag.rb
class UploadedFileTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :uploaded_file
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]
  validates :username, presence: true, uniqueness: true

  has_many :uploaded_files
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_uploaded_file

  def index
    out=@uploaded_file.comments.best.collect do |comment|
      user = comment.user
      parent_id = comment.parent_id ? comment.parent_id : "null"
      "{\"content\":\"#{comment.content}\", \"parent_id\":#{parent_id}, \"score\":#{comment.score}, \"id\": #{comment.id}, \"user\":{\"username\":\"#{user.username}\"}}"
      #{}"{\"content\":\"#{comment.content}\", \"parent_id\":#{parent_id}, \"score\":#{comment.score}, \"id\": #{comment.id}}"
    end.join(', ')
    render json: "[#{out}]"
  end

  private
  def set_uploaded_file
    @uploaded_file = UploadedFile.find_by(id: params[:uploaded_file_id])
  end
end

app/controllers/uploaded_files_controller.rb
class UploadedFilesController < ApplicationController

  before_action :set_uploaded_file, only: [:show, :download]
  before_action :set_uploaded_file_for_modify, only: [:edit, :update, :destroy]

  def index
    @uploaded_files = UploadedFile.all
  end

  def new
    render status: 403, text: 'You must create an account to upload files' if !current_user
    @uploaded_file = UploadedFile.new
  end

  def create
    render status: 403, text: 'You must create an account to upload files' if !current_user
    @uploaded_file = current_user.uploaded_files.build(uploaded_file_params)
    file = params[:uploaded_file][:file]
    @uploaded_file.file_type = file.content_type
    @uploaded_file.size = file.size
    @uploaded_file.name = file.original_filename
    if @uploaded_file.save
      File.open(Rails.root.join('public', 'uploads', "uploaded_file_#{@uploaded_file.id}"), 'wb') do |out_file|
        out_file.write(file.read)
      end
      @uploaded_file.path = "uploads/uploaded_file_#{@uploaded_file.id}"
      @uploaded_file.save
      redirect_to uploaded_file_path(@uploaded_file)
    end
  end

  def update
    @uploaded_file.update(uploaded_file_params)
    redirect_to uploaded_file_path(@uploaded_file)
  end

  def destroy
    FileUtils.rm_f "#{Rails.root}/public/#{@uploaded_file.path}"
    @uploaded_file.delete
    redirect_to uploaded_files_path
  end

  def download
    send_file("#{Rails.root}/public/#{@uploaded_file.path}", filename: @uploaded_file.name, type: @uploaded_file.file_type)
  end

  private
  def uploaded_file_params
    params.require(:uploaded_file).permit(:tags_str, :description)
  end
  def set_uploaded_file
    @uploaded_file = UploadedFile.find_by(id: params[:id])
  end

  def set_uploaded_file_for_modify
    @uploaded_file = UploadedFile.find_by(id: params[:id])
    @uploaded_file = nil if @uploaded_file.user != current_user
    render status: 404, text: "Not Found" if !@uploaded_file
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def destroy
    User.find(params[:id]).destroy
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div style="border: 1px solid black; margin-left: 5px; padding: 3px;">
<strong><%= comment.user.username %></strong> +<%=comment.score%><br>
<%= comment.content %>
<%= render comment.comments.best %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsFileServer</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div style="border: 1px solid black;display: inline-block;padding: 5px;">
    <%= link_to 'Browse Files', uploaded_files_path%>
    <% if current_user %>
      or <%= link_to 'Upload a File', new_uploaded_file_path%><br>
      Current user: <%= current_user.username %><br>
      <%= link_to 'Logout', destroy_user_session_path, method: 'DELETE' %>
      or <%= link_to 'Delete Account', user_path(current_user), method: 'DELETE' %>
    <% else %>
      <br><%= link_to 'Login', new_user_session_path %> or
      <%= link_to 'Signup', new_user_registration_path %>
    <% end %>
  </div><br>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>

</body>
</html>

app/views/uploaded_files/edit.html.erb
<%= form_for @uploaded_file do |f| %>
  <%= f.label :tags_str, 'Tags' %><br>
  <%= f.text_area :tags_str %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <br><%= f.submit "Save"%>
<% end %>

app/views/uploaded_files/index.html.erb
<ul>
  <% @uploaded_files.each do |file| %>
    <li><%= link_to file.name, uploaded_file_path(file) %> by <%=file.user.username%></li>
  <% end %>
</ul>

app/views/uploaded_files/new.html.erb
<%= form_for @uploaded_file do |f| %>
  <%= f.label :file %><br>
  <%= f.file_field :file %><br>
  <%= f.label :tags_str, 'Tags' %><br>
  <%= f.text_area :tags_str %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <br><%= f.submit "Upload File"%>
<% end %>

app/views/uploaded_files/show.html.erb
<div class="monospace">
<strong>Name: </strong><%= @uploaded_file.name %><br>
<strong>Desc: </strong><%= @uploaded_file.description %><br>
<strong>User: </strong><%= @uploaded_file.user.username %><br>
<strong>Type: </strong><%= @uploaded_file.file_type %><br>
<strong>Size: </strong><%= number_to_human_size @uploaded_file.size %><br>
<strong>Link: </strong><a href="/uploaded_files/<%= @uploaded_file.id %>/download">Download</a><br>
<strong>Tags: </strong>
<% @uploaded_file.tags.each do |tag, index| %>
  <%= tag.name %>,
<% end %>
<br>
<strong>Like: </strong>
<% @uploaded_file.related.each_with_index do |f, index| %>
  <%= link_to f.name, uploaded_file_path(f) %>,
<% end %><br>
<% if @uploaded_file.user == current_user %>
  <strong>Ctrl: </strong>
  <%= link_to 'Edit', edit_uploaded_file_path(@uploaded_file)%>
  <%= link_to 'Delete', uploaded_file_path(@uploaded_file), method: 'DELETE'%>
<% end %>
<p>Comments (<%= @uploaded_file.comments.count %>) <span style="float:right;" id="load-dbg">Loading</span></p>
<div id='comments'>
  <div class="loading"></div>
</div>
<script>
  $(()=>{
    var cStart = performance.now();
    $.get('/uploaded_files/<%= @uploaded_file.id %>/comments', (data)=>{
      renderComments(data)
      document.getElementById('load-dbg').innerHTML = Math.floor(performance.now()-cStart) + "ms";
    });
});
</script>
</div>